#!/bin/bash

# pandoc-runner - external filter called from mod_ext_filter module
# when a markdown file is requested

#>&2 echo $(printenv)

BASENAME=$(basename -s .md $DOCUMENT_URI)

/usr/bin/pandoc -f gfm -t html5 -c "/pandoc-gfm.css" \
	-T "Converted" -M title=${BASENAME}

#  -c /pandoc-gfm.css - this css used if it resides at apache document root
#  -T <title prefix>
#  -M title=<basename> - both together form "prefix - basename"
